### ISSUE TITLE
Do you any algorithm in Assembly Language?

### ISSUE THREAD

**Issue by abrahamcalf** [AllAlgorithms/assembly#3]
<p align="center">
  <img src="https://cdn.abraham.gq/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available, or in [Assembly](https://github.com/AllAlgorithms/assembly) this case

**Comment by cemysf** [comment]
I added KMP string search algorithm, which I have implemented a long while ago for a school homework. (PR #7 )
